import { Component, OnInit } from '@angular/core';
import { Container } from '../_models/container';
import { Item } from '../_models/item';

@Component({
  selector: 'app-demo',
  templateUrl: './demo.component.html',
  styleUrls: ['./demo.component.scss']
})
export class DemoComponent implements OnInit {
  container: Container =
    {
      "id": 3498,
      "sku": "BigBox1",
      "description": "Big Shipping Box",
      "xDim": 18,
      "yDim": 18,
      "zDim": 24,
      "volume": 7776,
      "units": "in"
    }

  items: Item[] = [
    {
      "id": 11035,
      "container": 3498,
      "sku": "ThingToShip1",
      "description": "Thing To Ship 1",
      "length": 17,
      "width": 4,
      "height": 4,
      "xDim": 4,
      "yDim": 4,
      "zDim": 17,
      "volume": 272,
      "xCenter": 2,
      "yCenter": 6,
      "zCenter": 8.5,
      "units": "in",
      "masterItemId": 4,
      "qty": 1
    },
    {
      "id": 11036,
      "container": 3498,
      "sku": "ThingToShip3",
      "description": "Thing To Ship 3",
      "length": 4,
      "width": 4,
      "height": 10,
      "xDim": 4,
      "yDim": 10,
      "zDim": 4,
      "volume": 160,
      "xCenter": 2,
      "yCenter": 9,
      "zCenter": 19,
      "units": "in",
      "masterItemId": 8,
      "qty": 1
    },
    {
      "id": 11037,
      "container": 3498,
      "sku": "ThingToShip3",
      "description": "Thing To Ship 3",
      "length": 4,
      "width": 4,
      "height": 10,
      "xDim": 4,
      "yDim": 10,
      "zDim": 4,
      "volume": 160,
      "xCenter": 2,
      "yCenter": 13,
      "zCenter": 2,
      "units": "in",
      "masterItemId": 13,
      "qty": 1
    },
    {
      "id": 11038,
      "container": 3498,
      "sku": "ThingToShip3",
      "description": "Thing To Ship 3",
      "length": 4,
      "width": 4,
      "height": 10,
      "xDim": 4,
      "yDim": 10,
      "zDim": 4,
      "volume": 160,
      "xCenter": 2,
      "yCenter": 13,
      "zCenter": 6,
      "units": "in",
      "masterItemId": 10,
      "qty": 1
    },
    {
      "id": 11039,
      "container": 3498,
      "sku": "ThingToShip3",
      "description": "Thing To Ship 3",
      "length": 4,
      "width": 4,
      "height": 10,
      "xDim": 4,
      "yDim": 10,
      "zDim": 4,
      "volume": 160,
      "xCenter": 2,
      "yCenter": 13,
      "zCenter": 10,
      "units": "in",
      "masterItemId": 12,
      "qty": 1
    },
    {
      "id": 11040,
      "container": 3498,
      "sku": "ThingToShip3",
      "description": "Thing To Ship 3",
      "length": 4,
      "width": 4,
      "height": 10,
      "xDim": 4,
      "yDim": 10,
      "zDim": 4,
      "volume": 160,
      "xCenter": 2,
      "yCenter": 13,
      "zCenter": 14,
      "units": "in",
      "masterItemId": 9,
      "qty": 1
    },
    {
      "id": 11041,
      "container": 3498,
      "sku": "ThingToShip3",
      "description": "Thing To Ship 3",
      "length": 4,
      "width": 4,
      "height": 10,
      "xDim": 10,
      "yDim": 4,
      "zDim": 4,
      "volume": 160,
      "xCenter": 5,
      "yCenter": 2,
      "zCenter": 2,
      "units": "in",
      "masterItemId": 11,
      "qty": 1
    },
    {
      "id": 11042,
      "container": 3498,
      "sku": "ThingToShip3",
      "description": "Thing To Ship 3",
      "length": 4,
      "width": 4,
      "height": 10,
      "xDim": 10,
      "yDim": 4,
      "zDim": 4,
      "volume": 160,
      "xCenter": 5,
      "yCenter": 2,
      "zCenter": 6,
      "units": "in",
      "masterItemId": 7,
      "qty": 1
    },
    {
      "id": 11043,
      "container": 3498,
      "sku": "ThingToShip2",
      "description": "Thing To Ship 2",
      "length": 11,
      "width": 11,
      "height": 11,
      "xDim": 11,
      "yDim": 11,
      "zDim": 11,
      "volume": 1331,
      "xCenter": 9.5,
      "yCenter": 9.5,
      "zCenter": 5.5,
      "units": "in",
      "masterItemId": 5,
      "qty": 1
    },
    {
      "id": 11044,
      "container": 3498,
      "sku": "ThingToShip2",
      "description": "Thing To Ship 2",
      "length": 11,
      "width": 11,
      "height": 11,
      "xDim": 11,
      "yDim": 11,
      "zDim": 11,
      "volume": 1331,
      "xCenter": 9.5,
      "yCenter": 9.5,
      "zCenter": 16.5,
      "units": "in",
      "masterItemId": 6,
      "qty": 1
    },
    {
      "id": 11045,
      "container": 3498,
      "sku": "ThingToShip1",
      "description": "Thing To Ship 1",
      "length": 17,
      "width": 4,
      "height": 4,
      "xDim": 17,
      "yDim": 4,
      "zDim": 4,
      "volume": 272,
      "xCenter": 8.5,
      "yCenter": 2,
      "zCenter": 10,
      "units": "in",
      "masterItemId": 1,
      "qty": 1
    },
    {
      "id": 11046,
      "container": 3498,
      "sku": "ThingToShip1",
      "description": "Thing To Ship 1",
      "length": 17,
      "width": 4,
      "height": 4,
      "xDim": 17,
      "yDim": 4,
      "zDim": 4,
      "volume": 272,
      "xCenter": 8.5,
      "yCenter": 2,
      "zCenter": 14,
      "units": "in",
      "masterItemId": 2,
      "qty": 1
    },
    {
      "id": 11047,
      "container": 3498,
      "sku": "ThingToShip1",
      "description": "Thing To Ship 1",
      "length": 17,
      "width": 4,
      "height": 4,
      "xDim": 17,
      "yDim": 4,
      "zDim": 4,
      "volume": 272,
      "xCenter": 8.5,
      "yCenter": 2,
      "zCenter": 18,
      "units": "in",
      "masterItemId": 3,
      "qty": 1
    }
  ]
  constructor() { }

  ngOnInit(): void {

  }

}
