import { Component, OnInit } from '@angular/core';
import { Container } from '../_models/container';
import { Item } from '../_models/item';

@Component({
  selector: 'app-demo',
  templateUrl: './demo.component.html',
  styleUrls: ['./demo.component.scss']
})
export class DemoComponent implements OnInit {
  container: Container =
    {
      "id": 185,
      "sku": "MyBigBox1",
      "description": "My Big Box",
      "xDim": 10.0,
      "yDim": 16.0,
      "zDim": 12.0,
      "volume": 1920.0,
      "units": "in"
    }

  items: Item[] = [
    {
      "id": 1152,
      "container": 185,
      "sku": "ThingToShip4",
      "description": "Thing To Ship 4",
      "length": 4.0,
      "width": 6.0,
      "height": 8.0,
      "xDim": 4.0,
      "yDim": 8.0,
      "zDim": 6.0,
      "volume": 192.0,
      "xCenter": 2.0,
      "yCenter": 4.0,
      "zCenter": 3.0,
      "units": "in",
      "masterItemId": 1137, "qty": 1
    },
    {
      "id": 1153,
      "container": 185,
      "sku": "ThingToShip4",
      "description": "Thing To Ship 4",
      "length": 4.0,
      "width": 6.0,
      "height": 8.0,
      "xDim": 4.0,
      "yDim": 8.0,
      "zDim": 6.0,
      "volume": 192.0,
      "xCenter": 2.0,
      "yCenter": 4.0,
      "zCenter": 9.0,
      "units": "in",
      "masterItemId": 1137, "qty": 1
    },
    {
      "id": 1154,
      "container": 185,
      "sku": "ThingToShip4",
      "description": "Thing To Ship 4",
      "length": 4.0,
      "width": 6.0,
      "height": 8.0,
      "xDim": 6.0,
      "yDim": 8.0,
      "zDim": 4.0,
      "volume": 192.0,
      "xCenter": 3.0,
      "yCenter": 12.0,
      "zCenter": 2.0,
      "units": "in",
      "masterItemId": 1137, "qty": 1
    },
    {
      "id": 1155,
      "container": 185,
      "sku": "ThingToShip4",
      "description": "Thing To Ship 4",
      "length": 4.0,
      "width": 6.0,
      "height": 8.0,
      "xDim": 6.0,
      "yDim": 8.0,
      "zDim": 4.0,
      "volume": 192.0,
      "xCenter": 3.0,
      "yCenter": 12.0,
      "zCenter": 6.0,
      "units": "in",
      "masterItemId": 1137, "qty": 1
    },
    {
      "id": 1156,
      "container": 185,
      "sku": "ThingToShip4",
      "description": "Thing To Ship 4",
      "length": 4.0,
      "width": 6.0,
      "height": 8.0,
      "xDim": 6.0,
      "yDim": 8.0,
      "zDim": 4.0,
      "volume": 192.0,
      "xCenter": 3.0,
      "yCenter": 12.0,
      "zCenter": 10.0,
      "units": "in",
      "masterItemId": 1137, "qty": 1
    },
    {
      "id": 1157,
      "container": 185,
      "sku": "ThingToShip1",
      "description": "Thing To Ship 1",
      "length": 3.0,
      "width": 4.0,
      "height": 5.0,
      "xDim": 4.0,
      "yDim": 5.0,
      "zDim": 3.0,
      "volume": 60.0,
      "xCenter": 6.0,
      "yCenter": 2.5,
      "zCenter": 10.5,
      "units": "in",
      "masterItemId": 1134, "qty": 1
    },
    {
      "id": 1158,
      "container": 185,
      "sku": "ThingToShip2",
      "description": "Thing To Ship 2",
      "length": 3.0,
      "width": 6.0,
      "height": 8.0,
      "xDim": 6.0,
      "yDim": 8.0,
      "zDim": 3.0,
      "volume": 144.0,
      "xCenter": 7.0,
      "yCenter": 4.0,
      "zCenter": 1.5,
      "units": "in",
      "masterItemId": 1135, "qty": 1
    },
    {
      "id": 1159,
      "container": 185,
      "sku": "ThingToShip2",
      "description": "Thing To Ship 2",
      "length": 3.0,
      "width": 6.0,
      "height": 8.0,
      "xDim": 6.0,
      "yDim": 8.0,
      "zDim": 3.0,
      "volume": 144.0,
      "xCenter": 7.0,
      "yCenter": 4.0,
      "zCenter": 4.5,
      "units": "in",
      "masterItemId": 1135, "qty": 1
    },
    {
      "id": 1160,
      "container": 185,
      "sku": "ThingToShip2",
      "description": "Thing To Ship 2",
      "length": 3.0,
      "width": 6.0,
      "height": 8.0,
      "xDim": 6.0,
      "yDim": 8.0,
      "zDim": 3.0,
      "volume": 144.0,
      "xCenter": 7.0,
      "yCenter": 4.0,
      "zCenter": 7.5,
      "units": "in",
      "masterItemId": 1135, "qty": 1
    },
    {
      "id": 1161,
      "container": 185,
      "sku": "ThingToShip3",
      "description": "Thing To Ship 3",
      "length": 4.0,
      "width": 4.0,
      "height": 4.0,
      "xDim": 4.0,
      "yDim": 4.0,
      "zDim": 4.0,
      "volume": 64.0,
      "xCenter": 8.0,
      "yCenter": 10.0,
      "zCenter": 2.0,
      "units": "in",
      "masterItemId": 1136, "qty": 1
    },
    {
      "id": 1162,
      "container": 185,
      "sku": "ThingToShip3",
      "description": "Thing To Ship 3",
      "length": 4.0,
      "width": 4.0,
      "height": 4.0,
      "xDim": 4.0,
      "yDim": 4.0,
      "zDim": 4.0,
      "volume": 64.0,
      "xCenter": 8.0,
      "yCenter": 10.0,
      "zCenter": 6.0,
      "units": "in",
      "masterItemId": 1136, "qty": 1
    },
    {
      "id": 1163,
      "container": 185,
      "sku": "ThingToShip1",
      "description": "Thing To Ship 1",
      "length": 3.0,
      "width": 4.0,
      "height": 5.0,
      "xDim": 4.0,
      "yDim": 5.0,
      "zDim": 3.0,
      "volume": 60.0,
      "xCenter": 8.0,
      "yCenter": 10.5,
      "zCenter": 9.5,
      "units": "in",
      "masterItemId": 1134, "qty": 1
    },
    {
      "id": 1164,
      "container": 185,
      "sku": "ThingToShip3",
      "description": "Thing To Ship 3",
      "length": 4.0,
      "width": 4.0,
      "height": 4.0,
      "xDim": 4.0,
      "yDim": 4.0,
      "zDim": 4.0,
      "volume": 64.0,
      "xCenter": 8.0,
      "yCenter": 14.0,
      "zCenter": 2.0,
      "units": "in",
      "masterItemId": 1136, "qty": 1
    },
    {
      "id": 1165,
      "container": 185,
      "sku": "ThingToShip3",
      "description": "Thing To Ship 3",
      "length": 4.0,
      "width": 4.0,
      "height": 4.0,
      "xDim": 4.0,
      "yDim": 4.0,
      "zDim": 4.0,
      "volume": 64.0,
      "xCenter": 8.0,
      "yCenter": 14.0,
      "zCenter": 6.0,
      "units": "in",
      "masterItemId": 1136, "qty": 1
    }
  ]
  constructor() { }

  ngOnInit(): void {

  }

}
